title: Safe Future HZT
description: "Safe Future - Kiber təqibə qarşı təhlükəsiz rəqəmsal gələcək"

url: "https://safefuture.site"
baseurl: ""

theme: null
markdown: kramdown
permalink: pretty

collections: []

defaults:
  - scope:
      path: ""
    values:
      layout: default

plugins: []
